### ISSUE TITLE
尝试在 6.1.88 下面编译驱动报错

### ISSUE THREAD

**Issue by achaoge** [britus/wk2xxx#1]
尝试编译驱动的时候报错，内核版本是 6.1.88，请问这个驱动适用的内核版本是哪个？:
![Screenshot from 2024-04-29 18-19-41](https://github.com/britus/wk2xxx/assets/168769/e519cba6-595a-45db-91ef-cc25f0ae0acf)

drivers/spi/spi-wk2xxx.c:1631:22: error: initialization of ‘void (*)(struct uart_port *, struct ktermios *, const struct ktermios *)’ from incompatible pointer type ‘void (*)(struct uart_port *, struct ktermios *, struct ktermios *)’ [-Werror=incompatible-pointer-types]
 1631 |         set_termios: wk2xxx_termios,
      |                      ^~~~~~~~~~~~~~
drivers/spi/spi-wk2xxx.c:1631:22: note: (near initialization for ‘wk2xxx_pops.set_termios’)
drivers/spi/spi-wk2xxx.c:2198:15: error: initialization of ‘void (*)(struct spi_device *)’ from incompatible pointer type ‘int (*)(struct spi_device *)’ [-Werror=incompatible-pointer-types]
 2198 |     .remove = wk2xxx_remove,
      |               ^~~~~~~~~~~~~
drivers/spi/spi-wk2xxx.c:2198:15: note: (near initialization for ‘wk2xxx_driver.remove’)

**Comment by britus** [comment]
Hello,
this driver is made for kernel https://github.com/britus/kernel-rk3568-ff-aio-ipc (4.19.232). Firefly just cheekily has a binary in the source kernel tree. I found the original driver source and adapted it for my kernel. If you want to use mainline 6, you have to port the source accordingly. The best thing is to make your work available to the kernel mainline too :)

Greetings

-- Google Translated - Chinese Traditinal --
你好，
該驅動程式是為核心 https://github.com/britus/kernel-rk3568-ff-aio-ipc (4.19.232) 製作的。 Firefly 厚臉皮地在來源內核樹中擁有二進位。我找到了原始驅動程式來源並將其改編為我的核心。如果你想使用主線6，你必須相應地移植來源。最好的事情是讓你的工作也可用於內核主線:)

問候
